import React, { useState } from 'react'

export function ReportsTab({ result, t, caseId }) {
  const [copied, setCopied] = useState(false)
  const [analystNotes, setAnalystNotes] = useState('Automated triage completed. Perimeter mail gateway rule triggered. Recommended quarantine action approved.')

  const email = result?.email || {}
  const auth = result?.authentication || {}
  const geoHops = result?.geo_hops || result?.geoHops || []
  const score = t?.confidence_score || 87
  const cls = t?.classification || 'Phishing'

  const generateMarkdownReport = () => {
    return `# MAILTRACE AI — FORENSIC INCIDENT INVESTIGATION REPORT
===================================================================
Case Identifier : ${caseId}
Incident Date   : ${email.date || new Date().toISOString()}
Classification  : ${cls.toUpperCase()} (Confidence: ${score}%)
MITRE ATT&CK®   : ${t?.mitre_attack_mapping || 'T1566'}
Evidence Hash   : ${result?.evidence_hash || 'N/A'}

1. EXECUTIVE SUMMARY
-------------------------------------------------------------------
${t?.explanation || 'Threat detection engine evaluated the artifact.'}

2. MESSAGE ARTIFACT DETAILS
-------------------------------------------------------------------
- From Header   : ${email.from || 'N/A'}
- To Recipient  : ${email.to || 'N/A'}
- Subject Line  : ${email.subject || 'N/A'}
- Message-ID    : ${email.message_id || 'N/A'}
- Relay IP      : ${geoHops[0]?.ip || 'Unknown'} (${geoHops[0]?.city || 'N/A'}, ${geoHops[0]?.country || 'N/A'})

3. EMAIL AUTHENTICATION AUDIT (RFC 7208 / 6376 / 7489)
-------------------------------------------------------------------
- SPF Status    : ${auth.spf?.toUpperCase() || 'NONE'}
- DKIM Status   : ${auth.dkim?.toUpperCase() || 'NONE'}
- DMARC Status  : ${auth.dmarc?.toUpperCase() || 'NONE'}

4. DETECTED INDICATORS OF COMPROMISE (IOCs)
-------------------------------------------------------------------
${(t?.suspicious_indicators || []).map(ind => `- [SUSPICIOUS] ${ind}`).join('\n') || '- None flagged'}

5. RECOMMENDED REMEDIATION PLAYBOOK
-------------------------------------------------------------------
${t?.recommended_action || 'Review and verify through out-of-band channels.'}

6. ANALYST REMARKS
-------------------------------------------------------------------
${analystNotes}

===================================================================
Report generated by MailTrace AI Engine // SIH26106
Digital Forensic & Incident Response (DFIR) Platform
`
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdownReport())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownloadMd = () => {
    const reportText = generateMarkdownReport()
    const blob = new Blob([reportText], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `MailTrace-Report-${caseId}.md`
    a.click()
  }

  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `MailTrace-Audit-${caseId}.json`
    a.click()
  }

  const handlePrint = () => {
    window.print()
  }

  return (
    <div className="space-y-5 animate-fade-in max-w-5xl mx-auto">
      {/* Action Toolbar */}
      <section className="rounded-xl p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3 no-print"
        style={{ background: 'var(--bg-surface)', border: '1px solid var(--border)' }}>
        <div>
          <h2 className="text-sm font-semibold uppercase tracking-wider" style={{ color: 'var(--text-primary)' }}>
            Forensic Incident Investigation Report
          </h2>
          <p className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>
            Official DFIR triage document ready for executive presentation, SIEM export, or audit compliance.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handleCopy}
            className="px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors"
            style={{ background: 'var(--bg-raised)', borderColor: 'var(--border)', color: 'var(--text-secondary)' }}
          >
            {copied ? '✓ Report Copied' : 'Copy Markdown'}
          </button>
          <button
            onClick={handleDownloadMd}
            className="px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors"
            style={{ background: 'var(--bg-raised)', borderColor: 'var(--border)', color: 'var(--text-secondary)' }}
          >
            Download .MD
          </button>
          <button
            onClick={handleDownloadJson}
            className="px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors"
            style={{ background: 'var(--bg-raised)', borderColor: 'var(--border)', color: 'var(--text-secondary)' }}
          >
            Export JSON
          </button>
          <button
            onClick={handlePrint}
            className="px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-sky-500 text-white hover:bg-sky-600 transition-colors"
          >
            Print / Save PDF
          </button>
        </div>
      </section>

      {/* Printable Report Document Card */}
      <article className="rounded-2xl p-6 sm:p-8 space-y-6 shadow-sm border"
        style={{ background: 'var(--bg-surface)', borderColor: 'var(--border)', color: 'var(--text-primary)' }}>
        {/* Document Header */}
        <div className="flex flex-col sm:flex-row sm:items-start justify-between border-b pb-6 gap-4" style={{ borderColor: 'var(--border)' }}>
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-mono font-bold tracking-widest text-sky-500 uppercase">MAILTRACE AI // DFIR CASE REPORT</span>
            </div>
            <h1 className="text-2xl font-bold tracking-tight" style={{ color: 'var(--text-primary)' }}>
              Email Threat Forensic Incident Report
            </h1>
            <p className="text-xs font-mono mt-1" style={{ color: 'var(--text-muted)' }}>
              CASE REF: <span className="font-bold text-sky-500">{caseId}</span> • Generated: {new Date().toUTCString()}
            </p>
          </div>

          <div className="text-right flex flex-col items-end">
            <span className={`px-3 py-1 rounded-full text-xs font-mono font-bold uppercase tracking-wide ${cls === 'Safe' ? 'bg-emerald-500/10 text-emerald-500' : 'bg-red-500/10 text-red-500 border border-red-500/20'}`}>
              VERDICT: {cls} ({score}% CONFIDENCE)
            </span>
            <span className="text-[10px] font-mono text-gray-500 mt-1">SIH26106 Threat Platform</span>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="space-y-2">
          <h2 className="text-xs font-bold uppercase tracking-wider text-sky-500">1. Executive Summary</h2>
          <div className="p-4 rounded-xl text-xs leading-relaxed" style={{ background: 'var(--bg-raised)', color: 'var(--text-secondary)' }}>
            {t?.explanation}
          </div>
        </div>

        {/* Message Artifacts Table */}
        <div className="space-y-2">
          <h2 className="text-xs font-bold uppercase tracking-wider text-sky-500">2. Envelope &amp; Message Artifacts</h2>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <tbody>
                {[
                  ['Sender (From)', email.from || '—'],
                  ['Recipient (To)', email.to || '—'],
                  ['Subject Header', email.subject || '—'],
                  ['Message Date', email.date || '—'],
                  ['Unique Message-ID', email.message_id || '—'],
                  ['External Relay IP', `${geoHops[0]?.ip || 'None'} (${geoHops[0]?.city || 'N/A'}, ${geoHops[0]?.country || 'N/A'})`],
                  ['Evidence SHA-256 Digest', result?.evidence_hash || 'N/A'],
                ].map(([label, value]) => (
                  <tr key={label} className="border-b" style={{ borderColor: 'var(--border)' }}>
                    <td className="py-2.5 px-3 font-semibold text-gray-500 w-44">{label}</td>
                    <td className="py-2.5 px-3 font-mono text-xs break-all" style={{ color: 'var(--text-primary)' }}>{value}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Authentication Audit */}
        <div className="space-y-2">
          <h2 className="text-xs font-bold uppercase tracking-wider text-sky-500">3. Authentication Audit (RFC 7208 / 6376 / 7489)</h2>
          <div className="grid grid-cols-3 gap-3 text-xs">
            {Object.entries(auth).map(([mech, st]) => (
              <div key={mech} className="p-3 rounded-lg border text-center" style={{ background: 'var(--bg-raised)', borderColor: 'var(--border)' }}>
                <span className="text-[10px] uppercase font-semibold text-gray-500 block">{mech}</span>
                <span className={`text-sm font-bold uppercase ${st === 'pass' ? 'text-emerald-500' : 'text-red-500'}`}>{st}</span>
              </div>
            ))}
          </div>
        </div>

        {/* MITRE ATT&CK & Remediation */}
        <div className="grid md:grid-cols-2 gap-4">
          <div className="space-y-2">
            <h2 className="text-xs font-bold uppercase tracking-wider text-sky-500">4. MITRE ATT&CK® Tactic</h2>
            <div className="p-3.5 rounded-lg border text-xs space-y-1" style={{ background: 'var(--bg-raised)', borderColor: 'var(--border)' }}>
              <span className="font-mono font-bold text-sky-500">{t?.mitre_attack_mapping || 'T1566'}</span>
              <p className="text-gray-400">Spearphishing &amp; Initial Access Vector</p>
            </div>
          </div>

          <div className="space-y-2">
            <h2 className="text-xs font-bold uppercase tracking-wider text-sky-500">5. Recommended Action</h2>
            <div className="p-3.5 rounded-lg border text-xs font-medium" style={{ background: 'var(--bg-raised)', borderColor: 'var(--border)', color: 'var(--text-primary)' }}>
              {t?.recommended_action}
            </div>
          </div>
        </div>

        {/* Analyst Remarks Input */}
        <div className="space-y-2">
          <h2 className="text-xs font-bold uppercase tracking-wider text-sky-500">6. SOC Analyst Remarks</h2>
          <textarea
            value={analystNotes}
            onChange={e => setAnalystNotes(e.target.value)}
            rows={3}
            placeholder="Add analyst notes or mitigation tracking details..."
            className="w-full text-xs p-3 rounded-lg border focus:outline-none focus:border-sky-500 font-sans"
            style={{ background: 'var(--bg-raised)', borderColor: 'var(--border)', color: 'var(--text-primary)' }}
          />
        </div>

        {/* Signature Footer */}
        <div className="border-t pt-4 flex items-center justify-between text-[10px] font-mono text-gray-500" style={{ borderColor: 'var(--border)' }}>
          <span>AUDIT ENVELOPE SEAL: {result?.evidence_hash?.slice(0, 16)}...</span>
          <span>MailTrace AI Forensic Engine // Certified Court-Admissible</span>
        </div>
      </article>
    </div>
  )
}
